from Player import Player

def main():
    player1 = Player("Alightenforce", "4040", "europe", 50)
    player1.update_profile()
    # player1.print_win_rate()
    # list = player1.determine_win_rate_with_person_on_team()
    # for player in list.values():
    #     print(player)
    # print(player1.calculate_win_rate_with_each_person_on_team())
    player1.print_winrate_with_allies()
    player1.print_winrate_of_enemies_against_player()
    #player1.get_all_player_info_in_match()
    # player1.print_win_rate_per_champion()
    # player1.print_average_kda_per_champion()
    # player1.print_champion_name_to_champion_mastery()
   #  player1.update_profile()
   #  player1.print_player_data()
   #  player1.print_player_data()
   #  player1.print_win_rate()
   #  player1.print_champion_name_to_champion_mastery()
   #  player1.print_side_bans()
   #  player1.print_win_rate_per_champion()
   #  player1.print_win_rate_per_champion()
   #  player1.print_average_kda_per_champion()
    #player2 = Player("Sloppy", "BOMB", "europe", 5)
    #player2.update_profile()
    # player2.print_player_data()
    # player2.print_side_bans()
    # print(player2.get_all_player_info_in_current_match())
    # print(player2.sort_current_match_champions_into_teams())
    # print(player2.get_champion_and_player_on_each_team_in_current_match())
    # player2.print_champions_in_current_match()
    #print(player2.print_win_rate())

if __name__ == "__main__":
    main()